/**************************************************************
 * Data buffer class -- See header file for more information. *
 **************************************************************/

#include "Buffer.h"

namespace AGSSock {

//------------------------------------------------------------------------------

void Buffer::extract()
{
	// Not checked for empty
	string &buffer = queue_.front();
	size_t pos = buffer.find_first_of('\0');
	if (pos == string::npos)
		queue_.pop();
	else
	{
		pos = buffer.find_first_not_of('\0', pos);
		buffer.erase(0, pos);
		// Empty strings should only be generated by the sockets API
		if (buffer.empty())
			queue_.pop();
	}
}

//------------------------------------------------------------------------------

} /* namespace AGSSock */

//..............................................................................
